


target'AixiangdaoDemo'do
platform:ios,'8.0'




 pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   'RCTText',
    'RCTImage',
   'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
 ]



  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

# Add new pods below this line



pod 'react-native-video', :path => '../node_modules/react-native-video'


pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

pod 'RNSVG', :path => '../node_modules/react-native-svg'

pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

pod 'react-native-amap-geolocation', path: '../node_modules/react-native-amap-geolocation/lib/ios'

pod 'SensorsAnalyticsSDK'



end
